### PR TITLE
add percentiles to summary output

### PR DESCRIPTION
**Pull request by JackKCWong**
image

I change the `Stat::new` to mutable borrow the input `vec` to avoid copying, except for the `xyplot` where original order matters. Let me know what you think. Cheers.

### CODE REVIEW

**Comment by JackKCWong** [comment]
tests passed.
image

**Comment by juan-leon** [comment]
Thanks for the pull requests.  Having percentiles is nice.

The Test pipeline failed (it seems fixable with `cargo fmt`).

If you have make tool installed you can do `make pre-commit` to make sure changes are OK.  Otherwise, this will do the job:

```
cargo fmt -- --check
cargo test -- --test-threads 1
cargo clippy -- -D clippy::all
```

**Comment by JackKCWong** [comment]
> cargo fmt -- --check

Should have run `make pre-commit`! Fixed now. Thanks.

**Comment by juan-leon** [comment]
Excellent!

Thanks for your contribution

**Comment by juan-leon** [comment]
Created release [v0.5.9](https://github.com/juan-leon/lowcharts/releases/tag/v0.5.9) with this change

**Pull request merged**
